"use client";
import { IconMapPinPlus, IconMessage, IconBug, IconFileDescription, IconInfoCircle, IconMail, IconBrandInstagram, IconArrowUpRight } from "@tabler/icons-react";
import Link from "next/link";
import type { Spot } from "@/types";
export default function AccountView(_props: { spots:Spot[];saved:Set<string>;distanceFor:(s:Spot)=>number;onOpen:(s:Spot)=>void;slugFor:(s:Spot)=>string|undefined;onFocus:(s:Spot)=>void }) {
 const menu=[{label:"Request a location",sub:"Tell us where Monday shouldn't find us",icon:IconMapPinPlus},{label:"Share feedback",sub:"Help us make Monday worse",icon:IconMessage},{label:"Report a bug",sub:"Something broke. Probably Monday's fault.",icon:IconBug},{label:"Terms & conditions",sub:"The boring stuff we legally have to say",icon:IconFileDescription},{label:"About us",sub:"We have a problem with Monday",icon:IconInfoCircle},{label:"Contact us",sub:"Got something to say?",icon:IconMail}];
 void _props;
 return <section className="amc-account-view"><div className="amc-instagram-follow"><span className="amc-instagram-kicker"><IconBrandInstagram size={16} stroke={2.4}/> outside monday</span><span className="amc-instagram-title">hate monday? you&apos;re one of us.</span><span className="amc-instagram-note">join the Anti Monday Club. follow us on instagram</span><a className="amc-instagram-handle" href="https://instagram.com/antimondayclub" target="_blank" rel="noopener noreferrer">@antimondayclub <IconArrowUpRight size={18} stroke={2.5}/></a></div><div className="amc-account-menu">{menu.map(({label,sub,icon:Icon})=>{const href=label==="Terms & conditions"?"/terms":label==="About us"?"/about":null;const content=<><span className="amc-menu-icon"><Icon size={19}/></span><span><strong>{label}</strong><small>{sub}</small></span><b>›</b></>;return href?<Link href={href} key={label}>{content}</Link>:<button type="button" key={label}>{content}</button>})}</div></section>;
}
